code/apps/blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path("article/", views.ArticleListView.as_view(), name="articles"),
    path("article/filter/<slug:category>/", views.ArticleFilterWithCategory.as_view(), name="article-list-category"),
    path("article/write/", views.ArticleCreateView.as_view(), name="write-article"),
    path("article/<slug:slug>/", views.ArticleDetailView.as_view(), name="article-detail"),
    path("article/<slug:slug>/edit/", views.ArticleUpdateView.as_view(), name="article-update"),
    path("article/<slug:slug>/delete/", views.ArticleDeleteView.as_view(), name="article-delete"),
    path("article/<slug:slug>/pin/", views.ArticlePinView.as_view(), name="article-pin"),
    path("article/<slug:slug>/comment/write/", views.CommentCreateView.as_view(), name="comment-create"),
    path("article/<slug:slug>/comment/<int:comment_id>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
    path("article/<slug:slug>/comment/<int:pk>/", views.CommentDetailView.as_view(), name="comment-detail"),
]

code/apps/core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.MainPageView.as_view(), name="home-page"),
    path("about-us/", views.AboutPageView.as_view(), name="about-us-page"),
    path("contact-us/", views.ContactPageView.as_view(), name="contact-us-page"),
    path("select2/categories/", views.CategoryAutocomplete.as_view(), name="categories-autocomplete"),
]

code/apps/qa/urls.py
from django.urls import path
from . import views

app_name = "qa"

urlpatterns = [
    path("question/",views.QuestionListView.as_view(),name="questions"),
    path("question/ask/",views.QuestionCreateView.as_view(),name="question-create"),
    path("question/<slug:slug>/",views.QuestionDetailView.as_view(),name="question-detail"),
    path("question/<slug:slug>/edit/",views.QuestionUpdateView.as_view(),name="question-update"),
    path("question/<slug:slug>/delete/",views.QuestionDeleteView.as_view(),name="question-delete"),
    path("question/<slug:slug>/like/",views.QuestionLikeView.as_view(),name="like-question"),
    path("question/<slug:slug>/dislike/",views.QuestionDisLikeView.as_view(),name="dislike-question"),
    path("question/<slug:slug>/answer/new",views.AnswerCreateView.as_view(),name="answer-create"),
    path("question/<slug:slug>/answer/<int:pk>/edit/",views.AnswerUpdateView.as_view(),name="answer-edit"),
    path("question/<slug:slug>/answer/<int:pk>/delete/",views.AnswerDeleteView.as_view(),name="answer-delete"),
    path("question/<slug:slug>/answer/<int:pk>/best/",views.AnswerBestView.as_view(),name="answer-best"),
    path("question/<slug:slug>/answer/<int:pk>/like/",views.AnswerLikeView.as_view(),name="answer-like"),
    path("question/<slug:slug>/answer/<int:pk>/dislike/",views.AnswerDisLikeView.as_view(),name="answer-dislike"),
]

code/config/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

django_urls = [
    path("admin/", admin.site.urls),
]
third_party_urls = [
    path("summernote/", include("django_summernote.urls")),
    path("select2/", include("django_select2.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
local_urls = [
    path("accounts/", include("apps.accounts.urls")),
    path("blog/", include("apps.blog.urls")),
    path("api/", include("apps.api.urls")),
    path("question-answer/", include("apps.qa.urls")),
    path("", include("apps.core.urls")),
]
urlpatterns = django_urls + third_party_urls + local_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/apps/qa/models.py
from django.utils.html import strip_tags
from django.db import models
from django.db.models import Count
from django.utils import timezone
from django.urls import reverse
from apps.accounts.models import CustomUser
from apps.core.models import BaseLike, BaseDisLike, Category




def upload_to_question(instance, filename):
    now = timezone.now()
    return f"qa/questions/{now:%Y/%m/%d}/{filename}"


class Question(models.Model):
    name = models.CharField("نام", max_length=110)
    help_image = models.ImageField(
        "تصویر کمکی", blank=True, null=True, upload_to=upload_to_question
    )
    question_description = models.TextField("توضیحات سوال", blank=True, null=True)
    is_active = models.BooleanField("فعال", default=True)
    solved = models.BooleanField("حل شده", default=False)
    is_pin = models.BooleanField("ویژه", default=False)
    write_date = models.DateTimeField("تاریخ مطرح شدن", auto_now_add=True)
    solve_date = models.DateTimeField("تاریخ حل شدن", blank=True, null=True)
    slug = models.SlugField("شناسه", unique=True)

    author = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="questions"
    )

    categories = models.ManyToManyField(Category, related_name="questions", verbose_name="دسته‌بندی‌ها")

    @property
    def stats(self):
        return (
            Question.objects.filter(id=self.id)
            .annotate(
                likes_count=Count("likes"),
                dislikes_count=Count("dislikes"),
            )
            .values("likes_count", "dislikes_count")
            .first()
        )

    @property
    def likes_count(self):
        return self.stats["likes_count"]

    @property
    def dislikes_count(self):
        return self.stats["dislikes_count"]

    @property
    def score(self):
        return self.likes_count - self.dislikes_count

    def solve(self):
        self.solved = True
        self.solve_date = timezone.now()
        self.save(update_fields=["solved", "solve_date"])

    def get_absolute_url(self):
        return reverse("qa:question-detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "سوال"
        verbose_name_plural = "سوالات"
        ordering = ["-write_date"]

    def __str__(self):
        return self.name


class Answer(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    answer_description = models.TextField("توضیحات پاسخ", blank=True, null=True)
    is_active = models.BooleanField("فعال", default=True)
    is_best = models.BooleanField("بهترین", default=False)
    write_date = models.DateTimeField("تاریخ مطرح شدن", auto_now_add=True)

    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answers"
    )

    @property
    def stats(self):
        return (
            Answer.objects.filter(id=self.id)
            .annotate(
                likes_count=Count("likes"),
                dislikes_count=Count("dislikes"),
            )
            .values("likes_count", "dislikes_count")
            .first()
        )

    @property
    def likes_count(self):
        return self.stats["likes_count"]

    @property
    def dislikes_count(self):
        return self.stats["dislikes_count"]

    @property
    def score(self):
        return self.likes_count - self.dislikes_count

    class Meta:
        verbose_name = "پاسخ"
        verbose_name_plural = "پاسخ‌ها"
        ordering = ["write_date"]

    def __str__(self):
        description = strip_tags(self.answer_description or "")
        if len(description) > 50:
            return f"{description[:50]}..."
        return description


class QLike(BaseLike):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="likes"
    )

    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "لایک‌ها"
        constraints = [
            models.UniqueConstraint(
                fields=["question", "user"], name="unique_user_like_question"
            )
        ]

    def __str__(self):
        return f"{self.user} liked {self.question}"


class QDisLike(BaseDisLike):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="dislikes"
    )

    class Meta:
        verbose_name = "دیس‌لایک"
        verbose_name_plural = "دیس‌لایک‌ها"
        constraints = [
            models.UniqueConstraint(
                fields=["question", "user"], name="unique_user_dislike_question"
            )
        ]

    def __str__(self):
        return f"{self.user} disliked {self.question}"


class ALike(BaseLike):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name="likes")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["answer", "user"], name="unique_user_like_answer"
            )
        ]

    def __str__(self):
        return f"{self.user} liked {self.answer}"


class ADisLike(BaseDisLike):
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, related_name="dislikes"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["answer", "user"], name="unique_user_dislike_answer"
            )
        ]

    def __str__(self):
        return f"{self.user} disliked {self.answer}"

code/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">

<head>
    <!-- Meta Tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta %}{% endblock meta %}

    <!-- Title -->
    <title>آزمایشگاه توسعه|{% block title %}{% endblock title %}</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="manifest" href="{% static 'images/site.webmanifest' %}">

    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    {% block styles %}{% endblock styles %}
</head>

<body data-theme="dark">
    <!-- Header Include -->
    {% include 'base/header.html' %}

    <main class="container py-4">
        <!-- Django Messages -->
        {% if messages %}
        <div class="mb-3">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% block content %}{% endblock content %}
    </main>

    <!-- Footer Include -->
    {% include 'base/footer.html' %}

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        crossorigin="anonymous"></script>
    <!-- Local -->
    <script src="{% static 'js/linkchecker.js' %}"></script>
    <script src="{% static 'js/hidemessage.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Summernote CSS/JS -->
    <link href="{% static 'summernote/summernote-bs5.min.css' %}" rel="stylesheet">
    <script src="{% static 'summernote/summernote-bs5.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#id_categories').select2({
                theme: 'default',
                width: '100%',
                ajax: {
                    url: "{% url 'core:categories-autocomplete' %}",
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return { q: params.term };
                    },
                    processResults: function (data) {
                        return { results: data.results };
                    },
                    cache: true
                },
                minimumInputLength: 3
            });

            $('.summernote').summernote({
                height: 480,
                lang: 'fa-IR',
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'italic', 'underline', 'clear']],
                    ['fontname', ['fontname']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['insert', ['link', 'picture', 'video', 'hr']],
                    ['view', ['fullscreen', 'codeview', 'help']]
                ]
            });
        });
    </script>
    {% block scripts %}{% endblock scripts %}
</body>

</html>

code/templates/base/footer.html
{% load static %}
<footer class="py-5 bg-dark text-light position-relative">
    <div class="container">
        <div class="row">

            <div class="col-6 col-md-2 mb-3">
                <h6>کاربردی برای توسعه</h6>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{% url 'blog:articles' %}"
                            class="nav-link p-0 text-secondary">بلاگ</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'qa:questions' %}"
                            class="nav-link p-0 text-secondary">پرسش و پاسخ</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'users' %}" class="nav-link p-0 text-secondary">کاربران</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">ای پی آی</a></li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h6>لینک های کمکی</h6>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{% url 'core:about-us-page' %}"
                            class="nav-link p-0 text-secondary">درباره ما</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'core:contact-us-page' %}"
                            class="nav-link p-0 text-secondary">تماس با ما</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">پشتیبانی</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">سوال های متداول</a></li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h6>با ما در ارتباط باشید!</h6>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="https://github.com/aboalfazlH"
                            class="nav-link p-0 text-secondary">گیتهاب</a></li>
                    <li class="nav-item mb-2"><a href="https://eitaa.com/developlab"
                            class="nav-link p-0 text-secondary">ایتا</a></li>
                    <li class="nav-item mb-2"><a href="https://ble.ir/developlab"
                            class="nav-link p-0 text-secondary">بله</a></li>
                    <li class="nav-item mb-2"><a href="https://rubika.ir/developlab"
                            class="nav-link p-0 text-secondary">روبیکا</a></li>
                </ul>
            </div>

            <div class="col-md-5 offset-md-1 mb-3">
                <h2>
                    توسعه میتونه ساده تر از این باشه
                </h2>
                <span>
                    هدف ما اینه به توسعه شما سرعت ببخشیم،از دوره های آموزشی و وبلاگ گرفته تا api و مخزن گیت و هاست.
                    {% if user.is_authenticated %}
                    {{ user.get_fullname }} اگر پیشنهادی داری،<a href="#">با ما در میان بگذار</a>
                    {% else %}
                    اگه شگفت زده شدی،<a href="{% url 'sign-up' %}">همین الان شروع کن!</a>
                    {% endif %}

                </span>
            </div>

        </div>

        <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top border-secondary">
            <p class="m-0">&copy; {% now "Y" %} تمام <a href="#">حقوق</a> محفوظ است.</p>
            <ul class="list-unstyled d-flex m-0">
                <li class="ms-3">
                    <a class="link-body-emphasis text-light" href="https://eitaa.com/developlab" aria-label="Eitaa">
                        <img height="50" width="50" src="{% static 'images/eitaa.png' %}" alt="Eitaa channel">
                    </a>
                </li>

                <li class="ms-3">
                    <a class="link-body-emphasis text-light" href="https://ble.ir/developlab"
                        style="position: relative; top: 4.5px;" aria-label="Bale">
                        <img height="40" width="40" src="{% static 'images/bale.png' %}" alt="Bale Channel">
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <a href="#" id="scrollToTop" class="btn btn-primary btn-lg position-absolute"
        style="right: 20px; bottom: 20px; border-radius: 50%;" aria-label="Scroll to Top">
        &#8593;
    </a>
</footer>

code/templates/base/header.html
<header class="p-3 text-bg-dark" dir="rtl">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-between">
            <span class="text-white fs-5 fs-sm-4 fs-md-3 fs-lg-2">
                آزمایشگاه توسعه
            </span>

            <button class="navbar-toggler btn btn-outline-light d-lg-none" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false"
                aria-label="Toggle navigation">
                ☰
            </button>

            <div class="collapse d-lg-flex flex-lg-wrap align-items-center justify-content-between w-100"
                id="navbarContent">
                <ul class="nav col-12 col-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'core:home-page' %}" class="nav-link px-2 text-secondary">صفحه اصلی</a></li>
                    <li><a href="{% url 'blog:articles' %}" class="nav-link px-2 text-white">بلاگ</a></li>
                    <li><a href="{% url 'core:about-us-page' %}" class="nav-link px-2 text-white">درباره ما</a></li>
                    <li><a href="{% url 'core:contact-us-page' %}" class="nav-link px-2 text-white">تماس با ما</a></li>
                </ul>

                <form class="d-flex align-items-center my-2 my-lg-0" role="search">
                    <input type="search" class="form-control form-control-dark bg-dark text-light me-2"
                        placeholder="جستجو..." />
                    <button type="submit" class="btn btn-outline-light">جستجو</button>
                </form>

                <div class="d-flex align-items-center gap-2 my-2 my-lg-0">
                    {% if user.is_authenticated %}
                    <a href="{% url 'user-profile' %}" class="btn btn-outline-light">{{ user }}</a>
                    <form action="{% url 'logout' %}" method="post" class="m-0">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">خروج</button>
                    </form>
                    {% if user.is_staff %}
                    <a href="{% url 'admin:index' %}" class="btn btn-primary">داشبورد</a>
                    {% endif %}
                    {% else %}
                    <a href="{% url 'login' %}" class="btn btn-outline-light">ورود</a>
                    <a href="{% url 'sign-up' %}" class="btn btn-warning">ثبت نام</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>