code/apps/qa/urls.py
from django.urls import path
from . import views

app_name = "qa"

urlpatterns = [
    path("question/",views.QuestionListView.as_view(),name="questions"),
    path("question/ask/",views.QuestionCreateView.as_view(),name="question-create"),
    path("question/<slug:slug>/",views.QuestionDetailView.as_view(),name="question-detail"),
    path("question/<slug:slug>/edit/",views.QuestionUpdateView.as_view(),name="question-update"),
    path("question/<slug:slug>/delete/",views.QuestionDeleteView.as_view(),name="question-delete"),
    path("question/<slug:slug>/like/",views.QuestionLikeView.as_view(),name="like-question"),
    path("question/<slug:slug>/dislike/",views.QuestionDisLikeView.as_view(),name="dislike-question"),
    path("question/<slug:slug>/answer/new",views.AnswerCreateView.as_view(),name="answer-create"),
    path("question/<slug:slug>/answer/<int:pk>/edit/",views.AnswerUpdateView.as_view(),name="answer-edit"),
    path("question/<slug:slug>/answer/<int:pk>/delete/",views.AnswerDeleteView.as_view(),name="answer-delete"),
    path("question/<slug:slug>/answer/<int:pk>/best/",views.AnswerBestView.as_view(),name="answer-best"),
    path("question/<slug:slug>/answer/<int:pk>/like/",views.AnswerLikeView.as_view(),name="answer-like"),
    path("question/<slug:slug>/answer/<int:pk>/dislike/",views.AnswerDisLikeView.as_view(),name="answer-dislike"),
]

code/config/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

django_urls = [
    path("admin/", admin.site.urls),
]
third_party_urls = [
    path("summernote/", include("django_summernote.urls")),
    path("select2/", include("django_select2.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
local_urls = [
    path("accounts/", include("apps.accounts.urls")),
    path("blog/", include("apps.blog.urls")),
    path("api/", include("apps.api.urls")),
    path("question-answer/", include("apps.qa.urls")),
    path("", include("apps.core.urls")),
]
urlpatterns = django_urls + third_party_urls + local_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/apps/qa/models.py
from django.utils.html import strip_tags
from django.db import models
from django.db.models import Count
from django.utils import timezone
from django.urls import reverse
from apps.accounts.models import CustomUser
from apps.core.models import BaseLike, BaseDisLike, Category




def upload_to_question(instance, filename):
    now = timezone.now()
    return f"qa/questions/{now:%Y/%m/%d}/{filename}"


class Question(models.Model):
    name = models.CharField("نام", max_length=110)
    help_image = models.ImageField(
        "تصویر کمکی", blank=True, null=True, upload_to=upload_to_question
    )
    question_description = models.TextField("توضیحات سوال", blank=True, null=True)
    is_active = models.BooleanField("فعال", default=True)
    solved = models.BooleanField("حل شده", default=False)
    is_pin = models.BooleanField("ویژه", default=False)
    write_date = models.DateTimeField("تاریخ مطرح شدن", auto_now_add=True)
    solve_date = models.DateTimeField("تاریخ حل شدن", blank=True, null=True)
    slug = models.SlugField("شناسه", unique=True)

    author = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="questions"
    )

    categories = models.ManyToManyField(Category, related_name="questions", verbose_name="دسته‌بندی‌ها")

    @property
    def stats(self):
        return (
            Question.objects.filter(id=self.id)
            .annotate(
                likes_count=Count("likes"),
                dislikes_count=Count("dislikes"),
            )
            .values("likes_count", "dislikes_count")
            .first()
        )

    @property
    def likes_count(self):
        return self.stats["likes_count"]

    @property
    def dislikes_count(self):
        return self.stats["dislikes_count"]

    @property
    def score(self):
        return self.likes_count - self.dislikes_count

    def solve(self):
        self.solved = True
        self.solve_date = timezone.now()
        self.save(update_fields=["solved", "solve_date"])

    def get_absolute_url(self):
        return reverse("qa:question-detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "سوال"
        verbose_name_plural = "سوالات"
        ordering = ["-write_date"]

    def __str__(self):
        return self.name


class Answer(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    answer_description = models.TextField("توضیحات پاسخ", blank=True, null=True)
    is_active = models.BooleanField("فعال", default=True)
    is_best = models.BooleanField("بهترین", default=False)
    write_date = models.DateTimeField("تاریخ مطرح شدن", auto_now_add=True)

    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answers"
    )

    @property
    def stats(self):
        return (
            Answer.objects.filter(id=self.id)
            .annotate(
                likes_count=Count("likes"),
                dislikes_count=Count("dislikes"),
            )
            .values("likes_count", "dislikes_count")
            .first()
        )

    @property
    def likes_count(self):
        return self.stats["likes_count"]

    @property
    def dislikes_count(self):
        return self.stats["dislikes_count"]

    @property
    def score(self):
        return self.likes_count - self.dislikes_count

    class Meta:
        verbose_name = "پاسخ"
        verbose_name_plural = "پاسخ‌ها"
        ordering = ["write_date"]

    def __str__(self):
        description = strip_tags(self.answer_description or "")
        if len(description) > 50:
            return f"{description[:50]}..."
        return description


class QLike(BaseLike):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="likes"
    )

    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "لایک‌ها"
        constraints = [
            models.UniqueConstraint(
                fields=["question", "user"], name="unique_user_like_question"
            )
        ]

    def __str__(self):
        return f"{self.user} liked {self.question}"


class QDisLike(BaseDisLike):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="dislikes"
    )

    class Meta:
        verbose_name = "دیس‌لایک"
        verbose_name_plural = "دیس‌لایک‌ها"
        constraints = [
            models.UniqueConstraint(
                fields=["question", "user"], name="unique_user_dislike_question"
            )
        ]

    def __str__(self):
        return f"{self.user} disliked {self.question}"


class ALike(BaseLike):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name="likes")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["answer", "user"], name="unique_user_like_answer"
            )
        ]

    def __str__(self):
        return f"{self.user} liked {self.answer}"


class ADisLike(BaseDisLike):
    answer = models.ForeignKey(
        Answer, on_delete=models.CASCADE, related_name="dislikes"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["answer", "user"], name="unique_user_dislike_answer"
            )
        ]

    def __str__(self):
        return f"{self.user} disliked {self.answer}"

code/apps/qa/forms.py
from django import forms
from .models import Question
from django_summernote.widgets import SummernoteWidget
from django_select2.forms import Select2MultipleWidget

class QuestionForm(forms.ModelForm):
    """Form definition for Question."""

    class Meta:
        """Meta definition for QuestionForm."""

        model = Question
        fields = ("name","help_image","question_description","slug","categories")
        widgets = {
            "question_description":SummernoteWidget(),
            "categories":Select2MultipleWidget()
        }        

code/apps/qa/views.py
from django.views.generic import (
    View,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib import messages
from .models import Question, Answer, QLike, QDisLike,ALike,ADisLike
from .forms import QuestionForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.timezone import now
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse


# Question views
class QuestionListView(ListView):
    model = Question
    template_name = "questions.html"
    context_object_name = "questions"
    paginate_by = 50
    ordering = "-write_date"

    def get_queryset(self):
        return Question.objects.filter(is_active=True).order_by("solved", "is_pin")


class QuestionDetailView(DetailView):
    model = Question
    template_name = "question_detail.html"
    slug_field = "slug"
    slug_url_kwarg = "slug"
    context_object_name = "question"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["answers"] = Answer.objects.filter(
            question=self.object,
        ).order_by("-write_date")
        return context


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    template_name = "write_question.html"
    form_class = QuestionForm

    def dispatch(self, request, *args, **kwargs):

        today = now().date()
        questions_today = Question.objects.filter(
            author=request.user, write_date__date=today
        )
        if questions_today.count() >= 50 and not (
            request.user.is_superuser
            or request.user.groups.filter(name="نویسندگان").exists()
        ):
            return HttpResponseForbidden("شما نمی‌توانید بیش از 50 سوال در روز بپرسید.")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user

        if form.instance.slug in ["question", "ask"]:
            form.add_error("slug", "این شناسه در دسترس نیست")
            return self.form_invalid(form)
        return super().form_valid(form)

    # TODO: if user has subscribe can ask 100 question and 1 question in month pin


class QuestionUpdateView(UpdateView):
    model = Question
    form_class = QuestionForm
    template_name = "question_update.html"

    def dispatch(self, request, *args, **kwargs):
        question = self.get_object()
        if not request.user.is_superuser and request.user != question.author:
            return HttpResponseForbidden("شما اجازه حذف این سوال را ندارید.")
        return super().dispatch(request, *args, **kwargs)


class QuestionDeleteView(DeleteView):
    model = Question
    template_name = "question_delete.html"
    context_object_name = "question"
    slug_field = "slug"
    slug_url_kwarg = "slug"
    success_url = reverse_lazy("qa:questions")

    def dispatch(self, request, *args, **kwargs):
        article = self.get_object()
        if not request.user.is_superuser and request.user != article.author:
            return HttpResponseForbidden("شما اجازه حذف این مقاله را ندارید.")
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        question = self.get_object()
        question.delete()
        return redirect(self.success_url)


class QuestionLikeView(View):
    def post(self, request, slug):
        q = Question.objects.get(slug=slug)

        QDisLike.objects.filter(user=request.user, question=q).delete()

        like, created = QLike.objects.get_or_create(user=request.user, question=q)
        if created:
            messages.success(request, "نظر شما با موفقیت ثبت شد")
        else:
            messages.info(request, "شما قبلاً لایک داده‌اید")

        return redirect("qa:questions")


class QuestionDisLikeView(View):
    def post(self, request, slug):
        q = Question.objects.get(slug=slug)

        QLike.objects.filter(user=request.user, question=q).delete()

        dislike, created = QDisLike.objects.get_or_create(user=request.user, question=q)
        if created:
            messages.success(request, "نظر شما با موفقیت ثبت شد")
        else:
            messages.info(request, "شما قبلاً دیسلایک داده‌اید")

        return redirect("qa:questions")


# Answer views
class AnswerCreateView(View):
    def post(self, request, slug):
        question = get_object_or_404(Question, slug=slug)
        content = request.POST.get("content")

        if not content:
            messages.error(request, "متن پاسخ نباید خالی باشد.")
            return redirect(question.get_absolute_url())

        Answer.objects.create(
            question=question, user=request.user, answer_description=content
        )

        messages.success(request, "پاسخ شما ثبت شد.")
        return redirect(question.get_absolute_url())


class AnswerUpdateView(UpdateView):
    model = Answer
    template_name = "edit_answer.html"
    fields = ["answer_description"]
    pk_url_kwarg = "pk"

    def get_success_url(self):
        question_slug = self.object.question.slug
        return reverse("qa:question-detail", kwargs={"slug": question_slug})


class AnswerDeleteView(LoginRequiredMixin, View):
    def post(self, request, slug, pk):
        answer = get_object_or_404(Answer, id=pk)

        if request.user == answer.user or request.user.is_superuser:
            answer.delete()
            messages.success(request, "پاسخ حذف شد.")
        else:
            messages.error(request, "شما اجازه حذف این پاسخ را ندارید.")

        return redirect("qa:question-detail", slug=slug)


class AnswerBestView(LoginRequiredMixin, View):
    def post(self, request, slug, pk):
        question = Question.objects.get(slug=slug)
        answer = get_object_or_404(Answer, id=pk)

        if Answer.objects.filter(
            question=question, is_active=True, is_best=True
        ).exists():
            messages.error(request, "این سوال یک پاسخ به عنوان بهترین دارد")
            return redirect("qa:question-detail", slug=slug)

        if request.user == question.author or request.user.is_superuser:
            answer.is_best = not answer.is_best
            answer.save()
            if answer.is_best:
                messages.success(request, "پاسخ به عنوان بهترین پاسخ انتخاب شد.")
            else:
                messages.success(request, "پاسخ دیگر بهترین نیست.")
        else:
            messages.error(
                request, "شما اجازه ندارید این پاسخ را به عنوان بهترین انتخاب کنید."
            )

        return redirect("qa:question-detail", slug=slug)


class AnswerLikeView(View):
    def post(self, request, pk, slug):
        a = Answer.objects.get(pk=pk)

        ADisLike.objects.filter(user=request.user, answer=a).delete()

        like, created = ALike.objects.get_or_create(user=request.user, answer=a)
        if created:
            messages.success(request, "نظر شما با موفقیت ثبت شد")
        else:
            messages.info(request, "شما قبلاً لایک داده‌اید")

        return redirect("qa:question-detail",slug=slug)


class AnswerDisLikeView(View):
    def post(self, request, pk,slug):
        a = Answer.objects.get(pk=pk)

        ALike.objects.filter(user=request.user, answer=a).delete()

        dislike, created = ADisLike.objects.get_or_create(user=request.user, answer=a)
        if created:
            messages.success(request, "نظر شما با موفقیت ثبت شد")
        else:
            messages.info(request, "شما قبلاً دیسلایک داده‌اید")

        return redirect("qa:question-detail",slug=slug)

code/apps/qa/templates/edit_answer.html
{% extends 'base/base.html' %}
{% block title %}
{% endblock title %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <textarea name="answer_description" class="summernote"></textarea>
    <button class="btn btn-primary" type="submit">تغییر</button>
</form>
{% endblock content %}

code/apps/qa/templates/question_delete.html
{% extends 'base/base.html' %}

{% block title %}
حذف {{ question }}
{% endblock title %}

{% block meta %}
{% endblock meta %}

{% block styles %}
{% endblock styles %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h2>مطمعنی میخوای {{ question }} رو حذف کنی؟</h2>
    
    <p>این عمل قابل جبران نیست</p>
    <button class="btn btn-danger" type="submit">بله</button>
    <a href="{% url 'qa:questions' %}" class="btn btn-info">خیر،برگرد</a>
</form>
{% endblock content %}

code/apps/qa/templates/question_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
{{ question }}
{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/questions.css' %}">    
{% endblock styles %}
    
{% block content %}
<div class="container my-5">
    <div class="card shadow-sm p-4">
        <h2 class="mb-3">{{ question.name }}</h2>

        {% if question.help_image %}
        <img src="{{ question.help_image.url }}" class="img-fluid rounded mb-3">
        {% endif %}

        <p class="mb-4">{{ question.question_description|safe }}</p>

        <div class="d-flex justify-content-between text-muted mb-3">
            <small>نویسنده: {{ question.author.username }}</small>
            <small>{{ question.write_date|date:"Y/m/d H:i" }}</small>
        </div>
        <h4 class="mt-4">پاسخ‌ها</h4>
        {% if answers %}
        {% for answer in answers %}
        <div class="card my-4 p-4 shadow-sm rounded border-1">
            <div class="vote-box">
                <form method="post" action="{% url 'qa:answer-like' question.slug answer.id %}" class="vote-btn">
                    {% csrf_token %}
                    <button type="submit" onclick="event.stopPropagation()" class="vote-action">▲</button>
                </form>

                <div>{{ answer.score }}</div>

                <form method="post" action="{% url 'qa:answer-dislike' question.slug answer.id %}" class="vote-btn">
                    {% csrf_token %}
                    <button type="submit" onclick="event.stopPropagation()" class="vote-action">▼</button>
                </form>
            </div>


            <div class="flex-grow-1">
                <h6 class="fw-bold mb-2">
                    {% if answer.is_best %}
                    <span class="badge bg-success me-1">بهترین</span>
                    {% endif %}
                </h6>

                <p class="mb-2">{{ answer.answer_description|safe }}</p>

                <small class="text-muted d-block">
                    {{ answer.write_date|date:"Y/m/d H:i" }} -
                    <span class="fw-bold">{{ answer.user.username }}</span>
                </small>

                <div class="mt-3">
                    <button class="btn btn-sm btn-outline-secondary me-1" style="display: inline;">گزارش</button>
                    {% if user == answer.user %}
                    <a href="{% url 'qa:answer-edit' question.slug answer.id %}" style="display: inline;"
                        class="btn btn-sm btn-outline-info">ویرایش</a>
                    <form method="post" action="{% url 'qa:answer-delete' question.slug answer.id %}">
                        {% csrf_token %}
                        <button style="display: inline;" type="submit"
                            class="btn btn-sm btn-outline-danger">حذف</button>
                    </form>
                    {% endif %}

                    {% if user == question.author or user.is_superuser %}
                    <form method="post" action="{% url 'qa:answer-best' question.slug answer.id %}">
                        {% csrf_token %}
                        <button style="display: inline;" type="submit" class="btn btn-sm btn-info">بهترین</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    {% else %}
    <p class="text-muted mt-3">هنوز پاسخی ثبت نشده است.</p>
    {% endif %}
    <form action="{% url 'qa:answer-create' question.slug %}" method="post" class="mb-4">
        {% csrf_token %}
        <textarea class="summernote" name="content" rows="3" style="height: 100px;width: suto;" required></textarea>
        <br>
        <button type="submit" class="btn btn-primary btn-sm">ارسال پاسخ</button>
    </form>
</div>
</div>
{% endblock content %}

code/apps/qa/templates/question_update.html
{% extends 'base/base.html' %}
{% block title %}
پرسیدن سوال
{% endblock title %}

{% block styles %}
{% endblock styles %}

{% block content %}
<h2>سوالت رو عوض کن!</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">تغییر سوال</button>
</form>
{% endblock content %}

code/apps/qa/templates/questions.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}لیست سوال‌ها{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/questions.css' %}">
{% endblock styles %}

{% block content %}
<div class="container my-5">
    <h3 class="mb-4">سوال‌ها</h3>

    {% if user.is_authenticated %}
    <a href="{% url 'qa:question-create' %}" class="btn btn-primary">تو هم بپرس</a>
    <hr>
    {% endif %}
    <div class="row">
        {% for question in questions %}
        <div class="col-md-12 mb-3" onclick="window.location='{{ question.get_absolute_url }}'">
            <div class="card p-3 d-flex flex-row align-items-start">
                <!-- Vote -->
                <div class="vote-box">
                    <form method="post" action="{% url 'qa:like-question' question.slug %}" class="vote-btn">
                        {% csrf_token %}
                        <button type="submit" onclick="event.stopPropagation()" class="vote-action">▲</button>
                    </form>

                    <div>{{ question.score }}</div>

                    <form method="post" action="{% url 'qa:dislike-question' question.slug %}" class="vote-btn">
                        {% csrf_token %}
                        <button type="submit" onclick="event.stopPropagation()" class="vote-action">▼</button>
                    </form>
                </div>

                <!-- Question Info -->
                <div class="flex-grow-1">
                    <h5><a href="{{ question.get_absolute_url }}">{{ question.name }}</a></h5>
                    <p class="text-muted mb-1">پرسش توسط <strong>{{ question.author }}</strong> در {{question.write_date|date:"M d, Y" }}</p>
                    <div class="mb-1">
                        {% for category in question.categories.all %}
                        <span style="background-color: {{ category.color }};" class="badge category-badge">{{ category.name }}</span>
                        {% endfor %}
                    </div> 
                    <div class="d-flex gap-2 flex-wrap">
                        {% if question.solved %}<span class="badge bg-success">حل شده</span>{% else %}<span
                            class="badge bg-warning text-dark">حل نشده</span>{% endif %}
                        {% if question.is_pin %}<span class="badge bg-info text-dark">ویژه</span>{% endif %}
                        <span class="badge bg-light text-dark">{{ question.answers.count }} پاسخ</span>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <p>هیچ سوالی ثبت نشده است.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

code/apps/qa/templates/write_question.html
{% extends 'base/base.html' %}
{% block title %}
پرسیدن سوال
{% endblock title %}

{% block styles %}
{% endblock styles %}

{% block content %}
<h2>سوال بپرس</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">ثبت سوال</button>
</form>
{% endblock content %}